/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basics;
import java.lang.Math;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class main {
    public static String pluralize(String str, int num){
        if (num ==1){
            return (str);
        }
        else{
            return (str + 's');
        }

    }
    public static void flipNHeads(int n){
        int flip=0;
        int numOfHead=0;
        int r=n;
        double rand;
        while (r>0){
            rand=Math.random();
            if(rand < 0.5){
                System.out.println("tails");
                flip ++;
                r=n;
                numOfHead=0;
            }
            else {
                System.out.println("heads");
                numOfHead ++;
                flip ++;
                r--;
            }
        }
        System.out.println("It took "+flip+" flips to flip "+numOfHead+" head in a row.");

    }
    public static void clock(){
        LocalDateTime now = LocalDateTime.now();
        while(true){
        int hour = now.getHour();
        int minute = now.getMinute();
        int second = now.getSecond();
        String time = now.format(DateTimeFormatter.ofPattern("HH:mm:ss"));
        System.out.println(time);
        }
    }
    public static void main(String[] args) {
        int dogCount = 1;
        System.out.println("I own " + dogCount + " " + pluralize("dog", dogCount) + ".");

        int catCount = 2;
        System.out.println("I own " + catCount + " " + pluralize("cat", catCount) + ".");

        int turtleCount = 0;
        System.out.println("I own " + turtleCount + " " + pluralize("turtle", turtleCount) + ".");
        flipNHeads(1);
        flipNHeads(2);
        clock();

    }

}
