/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;

import java.util.*;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test public void testAnalyzingWeatherData(){
        //input
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        /*  the out put shoud be :
        High: 72
        Low: 51
        Never saw temperature: 63
        Never saw temperature: 67
        Never saw temperature: 68
        Never saw temperature: 69
        */
        int max=72;
        int min = 51 ;
        String  neverSaw = "Never saw temperature: 63 \nNever saw temperature: 67\nNever saw temperature: 68\nNever saw temperature: 69";
        assertEquals(min,Library.analyzingWeatherData(weeklyMonthTemperatures),"Test for Analyzing Weather Data");


    }
    @Test public void tallyTest(){
        //input
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");

        /* the output should be
            Bush
         */

        assertEquals("Bush",Library.tally(votes),"Test for tally method");
    }
}
