/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        Restaurant r1 =new Restaurant("Restaurant 1",2.5);
        r1.addReview("the best","rawan alakhras",5);
        System.out.println(r1.tostring());
        r1.addReview("bad","rawan",0);
        System.out.println(r1.tostring());
    }
}
