/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;

public class App {
    public String getGreeting() {

        return "Hello World!";
    }
    public static int readFile(String path) throws IOException {
        int NumberOfError = 0 ;
        try {
            BufferedReader reader = new BufferedReader(new FileReader(path));
            Scanner scanner = new Scanner(reader);
            int lineNumber =1;
            while (scanner.hasNext()){
                String str = scanner.nextLine();

                if (str.endsWith("}") || str.endsWith("{") || str.contains("if") || str.contains("else") || str.isEmpty()){
                   // System.out.println("true");
                    lineNumber ++;
                }
                else if(!str.endsWith(";")){
                    System.out.println("Line "+lineNumber+": Missing semicolon.");
                    lineNumber++;
                    NumberOfError++;
                    //System.out.println("false");
                }
                else {
                    lineNumber++;
                }


                //System.out.println(scanner.nextLine());
            }
        } catch (FileNotFoundException exception){
            System.out.println("The provided file path/name caused a file not found exception");
        }



        return NumberOfError;
        }

    public static void main(String[] args) throws IOException{
        String path ="C:\\Users\\user\\LTUC\\java-fundamentals\\linter\\app\\src\\main\\resources\\gates.js";

        readFile(path);
    }
}
