/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    Restaurant r1;
    Review r2;

    @BeforeEach public void inti(){
        r1=new Restaurant("Restaurant 1",1);
        r2=new Review("the best","rawan alakhras",5);
    }
    @Test public void testRestaurantConstructor(){
        assertNotNull(r1);
    }
    @Test public void testReviewConstructor(){
        assertNotNull(r2);
    }

    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test void testRestaurantToString(){

        String str = r1.tostring();
        assertEquals("the name of Restaurant is:"+"Restaurant 1"+
        "\nthe number of stars is :"+0+
                "\nprice category:"+1.0+"\nThe Review details\n",str);

    }

    @Test void  testReviewTostring(){

        String str=r2.tostring();
        assertEquals("the author is:"+"rawan alakhras"+
        "\nthe body of review :"+"the best\n"+
                "number Of Stars :"+5,str);

    }
    @Test void testAddReview(){
        r1.addReview(r2.body,r2.author,r2.stars);
        int size=r1.addReview("bad","rawan",0);
        //test number of review in a resturant
        assertEquals(2,size);
        assertTrue(r1.numberOfStars>0);
    }
    @Test void testUpdate(){
        assertTrue(r1.numberOfStars==0);
        r1.addReview(r2.body,r2.author,r2.stars);
        int size=r1.addReview("bad","rawan",0);
        assertTrue(r1.numberOfStars>0);
    }


}
