/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basics;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class mainTest {
    @Test void appHasAGreeting() {
        main classUnderTest = new main();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
